### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('sklearnscikits.audiolab')

### ISSUE THREAD

**Issue by GreatJiweix** [zzw922cn/Automatic_Speech_Recognition#68]
I encountered this problem during the process of running the program. Would you like to know if I have any idea why? Thank you very much.error: Could not find suitable distribution for Requirement.parse('sklearnscikits.audiolab')

**Comment by zzw922cn** [comment]
@GreatJiweix Hello, I am sorry for too busy to reply you asap. I have updated the code in TIMIT preprocess. Since audiolab has not been updated several years and my project is written in Python3.5, we can use another tool to convert NIST to wav, for example, in core folder, i have supplied the nist2wav.sh, you can try it.

**Comment by GreatJiweix** [comment]
Hello, thank you very much for your reply. I tried your method and still can't convert the original TIMIT data to the mfcc and label folders needed by the program. I don't know if you can provide a copy of the mfcc and Label's timit dataset download address, thank you very much.




------------------ 原始邮件 ------------------
发件人: "zzw922cn"<notifications@github.com>;
发送时间: 2018年4月3日(星期二) 中午12:17
收件人: "zzw922cn/Automatic_Speech_Recognition"<Automatic_Speech_Recognition@noreply.github.com>;
抄送: "532033961"<532033961@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [zzw922cn/Automatic_Speech_Recognition] error: Could not findsuitable distribution for Requirement.parse('sklearnscikits.audiolab') (#68)




@GreatJiweix Hello, I am sorry for too busy to reply you asap. I have updated the code in TIMIT preprocess. Since audiolab has not been updated several years and my project is written in Python3.5, we can use another tool to convert NIST to wav, for example, in core folder, i have supplied the nist2wav.sh, you can try it.
